## Classwork 4

Perceptron algorithm on the Iris data set

---

1. Read the Iris data set into Python. It is available in `Iris.csv` in the DataSets folder. Labels are in the column named 'species'. They are 0, 1, or 2, depending on the species of iris flower.
> The Iris data set can also be obtained by using the Python package Scikit-learn. You need this package installed first; once you have done that, you may simply put in the command: `sklearn.datasets.load_iris()`. This returns a dictionary object (technically, a "bunch"). From that "bunch", the keys 'data', and 'target', will give you the x vectors in $\mathbb R^4$, and the y labels, respectively.

In [1]:
import sklearn
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data_bunch = sklearn.datasets.load_iris()
iris = data_bunch['data']
iris_target = data_bunch['target']

In [4]:
iris[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
iris_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
np.count_nonzero(iris_target)

100

2. Make new y-labels so that any data point from species 0 now has y-label 1 (these are the first 50 data points), and make the other y-labels equal to -1.

In [ ]:
ylabels = np.array([1]*50 + [-1]*100)

3. Define a Perceptron algorithm (custom) function, that implements the algorithm described in the pseudo-code block in the Lecture 7 slides. Talk with others. Try to make your code as efficient as possible!

In [ ]:
def perceptron(x, y):
    X = np.hstack((np.ones(150).reshape(-1,1), iris))
    W = np.zeros(X.shape[1])
    products = y*(X@W)
    # put in a while...

array([[1. , 5.1, 3.5, 1.4, 0.2],
       [1. , 4.9, 3. , 1.4, 0.2],
       [1. , 4.7, 3.2, 1.3, 0.2],
       [1. , 4.6, 3.1, 1.5, 0.2],
       [1. , 5. , 3.6, 1.4, 0.2]])

4. Run your code on the Iris data and determine the coefficients $\textbf{w}$ and $b$ for a hyperplane that separates the labeled data. 